<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB; //追記

class QuizDataTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //テーブルのクリア
        DB::table('quizData')->truncate();

        //初期データ用意(列名をキーとする連想配列)
        DB::table('quizData')->insert([
            [ 'language' => 'ミャンマー語', 
              'question' => 'ミャンマー語で「こんにちは」は？',
              'answer' => 'ミンガラーバー', 
              'choice1' => 'クムスタカ', 
              'choice2' => 'シンチャオ', 
              'choice3' => 'ズドラーボ', 
              'choice4' => 'ミンガラーバー', 
              'pathPronunciation' => '/sound/hello_myanmar.m4a', 
              'pathBackground' => '../image/myanmar/danceByEveryone.jpg', 
              'subLanguage' => '', 
              'jpGreetingWord' => '', 
            ],
            [ 'language' => 'ミャンマー語', 
              'question' => 'ミャンマー語で「ありがとう」は？',
              'answer' => 'ティーズーべー', 
              'choice1' => 'ティーズーべー', 
              'choice2' => 'ガモン', 
              'choice3' => 'コープンカップ', 
              'choice4' => 'サラマットゥ', 
              'pathPronunciation' => '/sound/thankyou_myanmar.m4a', 
              'pathBackground' => '../image/myanmar/danceByEveryone.jpg', 
              'subLanguage' => '', 
              'jpGreetingWord' => '', 
            ],
            [ 'language' => 'ミャンマー語', 
              'question' => 'ミャンマー語で「さよなら」は？',
              'answer' => 'タッター', 
              'choice1' => 'ティーズーべー', 
              'choice2' => 'ガモン', 
              'choice3' => 'コープンカップ', 
              'choice4' => 'タッター', 
              'pathPronunciation' => '', 
              'pathBackground' => '../image/myanmar/danceByEveryone.jpg', 
              'subLanguage' => '', 
              'jpGreetingWord' => '', 
            ],

            [ 'language' => 'ミャンマー語', 
              'question' => 'ミャンマー語で「お会いできて嬉しいです」は？',
              'answer' => 'トゥエヤダワンターバーデー', 
              'choice1' => 'ズドラーボ', 
              'choice2' => 'クムスタポカヨ', 
              'choice3' => 'トゥエヤダワンターバーデー', 
              'choice4' => 'クムスタポカヨ', 
              'pathPronunciation' => '', 
              'pathBackground' => '../image/myanmar/shwedagonPagoda.jpg', 
              'subLanguage' => '', 
              'jpGreetingWord' => '', 
            ],

            [ 'language' => 'ミャンマー語', 
              'question' => 'ミャンマー語で「元気ですか？」は？',
              'answer' => 'ネカウンラー', 
              'choice1' => 'クムスタカ', 
              'choice2' => 'クムスタポカヨ', 
              'choice3' => 'ネカウンテー', 
              'choice4' => 'ネカウンラー', 
              'pathPronunciation' => '', 
              'pathBackground' => '../image/myanmar/danceByEveryone.jpg', 
              'subLanguage' => '', 
              'jpGreetingWord' => '', 
            ],
            [ 'language' => 'ミャンマー語', 
              'question' => 'ミャンマー語で「よい1日は？」は？',
              'answer' => 'カウントォー ネィレイビイェバァスィ', 
              'choice1' => 'タナジャバキャミャア', 
              'choice2' => 'ネカウンテー?', 
              'choice3' => 'アヤダァ  シーデー', 
              'choice4' => 'カウントォー ネィレイビイェバァスィ', 
              'pathPronunciation' => '/sound/haveaniceday_myanmar.m4a', 
              'pathBackground' => '../image/myanmar/shwedagonPagoda.jpg', 
              'subLanguage' => '', 
              'jpGreetingWord' => '', 
            ],

            [ 'language' => 'ミャンマー語', 
              'question' => 'ミャンマー語で「ご飯は食べましたか？」は？',
              'answer' => 'タミィン サーピィ ビ ラ', 
              'choice1' => 'ネカウンラー', 
              'choice2' => 'タミィン サーピィ ビ ラ', 
              'choice3' => 'ネカウンテー', 
              'choice4' => 'カウントォー ネィレイビイェバァスィ', 
              'pathPronunciation' => '', 
              'pathBackground' => '../image/myanmar/danceByEveryone.jpg', 
              'subLanguage' => '', 
              'jpGreetingWord' => '', 
            ],

            [ 'language' => 'ミャンマー語', 
              'question' => 'ミャンマー語で「おやすみ」は？',
              'answer' => 'カントンニャーバー', 
              'choice1' => 'タッター', 
              'choice2' => 'マサブゥ', 
              'choice3' => 'ナゥマトウェ ジャメェ', 
              'choice4' => 'カントンニャーバー', 
              'pathPronunciation' => '', 
              'pathBackground' => '../image/myanmar/shwedagonPagoda.jpg', 
              'subLanguage' => '', 
              'jpGreetingWord' => '', 
            ],

            [ 'language' => 'ミャンマー語', 
              'question' => 'ミャンマー語で「また会いましょう」は？',
              'answer' => 'ナゥマトウェ ジャメェ', 
              'choice1' => 'カントンニャーバー', 
              'choice2' => 'ナゥマトウェ ジャメェ', 
              'choice3' => 'クムスタポカヨ', 
              'choice4' => 'カウントォー ネィレイビイェバァスィ', 
              'pathPronunciation' => '', 
              'pathBackground' => '../image/myanmar/danceByEveryone.jpg', 
              'subLanguage' => '', 
              'jpGreetingWord' => '', 
            ],

            [ 'language' => 'ミャンマー語', 
              'question' => 'ミャンマー語で「少し」は？',
              'answer' => 'ネネ', 
              'choice1' => 'ニン', 
              'choice2' => 'アミャージー', 
              'choice3' => 'ネネ', 
              'choice4' => 'バタァ', 
              'pathPronunciation' => '', 
              'pathBackground' => '../image/myanmar/danceByEveryone.jpg', 
              'subLanguage' => '', 
              'jpGreetingWord' => '', 
            ],

            [ 'language' => 'ミャンマー語', 
              'question' => 'ミャンマー語で「美味しい」は？',
              'answer' => 'アヤダア シーデー', 
              'choice1' => 'マ サァブゥー', 
              'choice2' => 'サービィ', 
              'choice3' => 'タミィン', 
              'choice4' => 'アヤダア シーデー', 
              'pathPronunciation' => '', 
              'pathBackground' => '../image/myanmar/danceByEveryone.jpg', 
              'subLanguage' => '', 
              'jpGreetingWord' => '', 
            ],

            [ 'language' => 'ミャンマー語', 
              'question' => 'ミャンマー語で「食べた」は？',
              'answer' => 'サービィ ビ', 
              'choice1' => 'マ サァブゥー', 
              'choice2' => 'イヤダア シーデー', 
              'choice3' => 'ナァブゥー', 
              'choice4' => 'サービィ ビ', 
              'pathPronunciation' => '', 
              'pathBackground' => '../image/myanmar/danceByEveryone.jpg', 
              'subLanguage' => '', 
              'jpGreetingWord' => '', 
            ],

            [ 'language' => 'ミャンマー語', 
              'question' => 'ミャンマー語で「食べない」は？',
              'answer' => 'マ サァブゥー', 
              'choice1' => 'イヤダア シーデー', 
              'choice2' => 'サービィ ビ', 
              'choice3' => 'イヤダア シーデー', 
              'choice4' => 'マ サァブゥー', 
              'pathPronunciation' => '', 
              'pathBackground' => '../image/myanmar/danceByEveryone.jpg', 
              'subLanguage' => '', 
              'jpGreetingWord' => '', 
            ],

            [ 'language' => 'ミャンマー語', 
              'question' => 'ミャンマー語で「すみません」は？',
              'answer' => 'ホウレ', 
              'choice1' => 'クインルッパー', 
              'choice2' => 'ホウレ', 
              'choice3' => 'ダウンベン バデー', 
              'choice4' => 'タナジャバキャミャア', 
              'pathPronunciation' => '', 
              'pathBackground' => '../image/myanmar/danceByEveryone.jpg', 
              'subLanguage' => '', 
              'jpGreetingWord' => '', 
            ],

            [ 'language' => 'ミャンマー語', 
              'question' => 'ミャンマー語で「綺麗」は？',
              'answer' => 'ラァッデェー', 
              'choice1' => 'ラァッデェー', 
              'choice2' => 'チッチ', 
              'choice3' => 'ホウレ', 
              'choice4' => 'チッボエカウンデー', 
              'pathPronunciation' => '', 
              'pathBackground' => '../image/myanmar/danceByEveryone.jpg', 
              'subLanguage' => '', 
              'jpGreetingWord' => '', 
            ],

            [ 'language' => 'ミャンマー語', 
              'question' => 'ミャンマー語で「かわいい」は？',
              'answer' => 'チッボォカウンデー', 
              'choice1' => 'イヤダア シーデー', 
              'choice2' => 'ダウンベン バデー', 
              'choice3' => 'チッボォカウンデー', 
              'choice4' => 'クラッデェー', 
              'pathPronunciation' => '', 
              'pathBackground' => '../image/myanmar/shwedagonPagoda.jpg', 
              'subLanguage' => '', 
              'jpGreetingWord' => '', 
            ],

            [ 'language' => 'ミャンマー語', 
              'question' => 'ミャンマー語で「いくらですか？」は？',
              'answer' => 'バ ラォ レー？', 
              'choice1' => 'ベ ラォ チッレー', 
              'choice2' => 'アミャージー？', 
              'choice3' => 'ネネ？', 
              'choice4' => 'バ ラォ レー？', 
              'pathPronunciation' => '', 
              'pathBackground' => '../image/myanmar/shwedagonPagoda.jpg', 
              'subLanguage' => '', 
              'jpGreetingWord' => '', 
            ],

            [ 'language' => 'ミャンマー語', 
              'question' => 'ミャンマー語で「朝」は？',
              'answer' => 'マァネ', 
              'choice1' => 'マァネ', 
              'choice2' => 'ニャア', 
              'choice3' => 'ネキィン', 
              'choice4' => 'ミンガラーバ', 
              'pathPronunciation' => '', 
              'pathBackground' => '../image/myanmar/shwedagonPagoda.jpg', 
              'subLanguage' => '', 
              'jpGreetingWord' => '', 
            ],

            [ 'language' => 'ミャンマー語', 
              'question' => 'ミャンマー語で「昼」は？',
              'answer' => 'ネキィン', 
              'choice1' => 'ネキィン', 
              'choice2' => 'ミンガラーバー', 
              'choice3' => 'ニャア', 
              'choice4' => 'マァネ', 
              'pathPronunciation' => '', 
              'pathBackground' => '../image/myanmar/shwedagonPagoda.jpg', 
              'subLanguage' => '', 
              'jpGreetingWord' => '', 
            ],

            [ 'language' => 'ミャンマー語', 
              'question' => 'ミャンマー語で「夜」は？',
              'answer' => 'ニャア', 
              'choice1' => 'マァネ', 
              'choice2' => 'ニャア', 
              'choice3' => 'ネキィン', 
              'choice4' => 'ミンガラーバー', 
              'pathPronunciation' => '', 
              'pathBackground' => '../image/myanmar/shwedagonPagoda.jpg', 
              'subLanguage' => '', 
              'jpGreetingWord' => '', 
            ],

            [ 'language' => 'ミャンマー語', 
              'question' => 'ミャンマー語で「申し訳ありません」は？',
              'answer' => 'タウンパンバーデー', 
              'choice1' => 'タウンパンバーデー', 
              'choice2' => 'ソーリーベーノー', 
              'choice3' => 'クインルッパー', 
              'choice4' => 'ホウレ', 
              'pathPronunciation' => '', 
              'pathBackground' => '../image/myanmar/shwedagonPagoda.jpg', 
              'subLanguage' => '', 
              'jpGreetingWord' => '', 
            ],
            [ 'language' => 'ミャンマー語', 
              'question' => 'ミャンマー語で「ごめんなさい」は？',
              'answer' => 'ソーリーベーノー', 
              'choice1' => 'タウンパンバーデー', 
              'choice2' => 'ソーリーベーノー', 
              'choice3' => 'クインルッパー', 
              'choice4' => 'ホウレ', 
              'pathPronunciation' => '', 
              'pathBackground' => '../image/myanmar/shwedagonPagoda.jpg', 
              'subLanguage' => '', 
              'jpGreetingWord' => '', 
            ],
            
           
            [ 'language' => 'ミャンマー語',            
              'question' => 'ミャンマー語で「冗談冗談」は？',
              'answer' => 'サダサダ', 
              'choice1' => 'イマチョブラ', 
              'choice2' => 'シンメェイ', 
              'choice3' => 'パロレ', 
              'choice4' => 'サダサダ', 
              'pathPronunciation' => '', 
              'pathBackground' => '../image/myanmar/danceByEveryone.jpg', 
              'subLanguage' => '', 
              'jpGreetingWord' => '', 
            ],
            [ 'language' => 'ミャンマー語',            
              'question' => 'ミャンマー語で「痛いの痛いの飛んでいけ」は？',
              'answer' => 'オンプゥワー', 
              'choice1' => 'ロンジィー', 
              'choice2' => 'オンプゥワー', 
              'choice3' => 'パソｫｰ', 
              'choice4' => 'タメィー', 
              'pathPronunciation' => '', 
              'pathBackground' => '../image/myanmar/shwedagonPagoda.jpg',
              'subLanguage' => '', 
              'jpGreetingWord' => '', 
            ], 

            [ 'language' => 'ミャンマー語',            
              'question' => 'ミャンマー語で「（フランクな感じでの）美味しい」は？',
              'answer' => 'サァロォ カゥンディー', 
              'choice1' => 'アヤダア シーデー', 
              'choice2' => 'タミィン サービィ ビ ラ', 
              'choice3' => 'サァロォ カゥンディー', 
              'choice4' => 'チッボォカウンデー', 
              'pathPronunciation' => '', 
              'pathBackground' => '../image/myanmar/shwedagonPagoda.jpg', 
              'subLanguage' => '', 
              'jpGreetingWord' => '', 
            ],
            [ 'language' => 'ミャンマー語',            
              'question' => 'ミャンマー語で「ジャジャーン（魔法で何かを出すみたいな時）」は？',
              'answer' => 'ハチャラゥーン', 
              'choice1' => 'ヨォン バー', 
              'choice2' => 'タナジャバキャミャア', 
              'choice3' => 'チッボエカウンデー', 
              'choice4' => 'ハチャラゥーン', 
              'pathPronunciation' => '', 
              'pathBackground' => '../image/myanmar/danceByEveryone.jpg', 
              'subLanguage' => '', 
              'jpGreetingWord' => '', 
            ],
            [ 'language' => 'ミャンマー語',            
              'question' => 'ミャンマー語で「大丈夫」は？',
              'answer' => 'ヤデ', 
              'choice1' => 'ヤッピー', 
              'choice2' => 'ヤデ', 
              'choice3' => 'デケエ', 
              'choice4' => 'ハチャラゥーン', 
              'pathPronunciation' => '', 
              'pathBackground' => '../image/myanmar/danceByEveryone.jpg', 
              'subLanguage' => '', 
              'jpGreetingWord' => '', 
            ],
            [ 'language' => 'ミャンマー語',            
              'question' => 'ミャンマー語で「本当（ほんま）」は？',
              'answer' => 'デケエ', 
              'choice1' => 'ヤッピー', 
              'choice2' => 'ヤデ', 
              'choice3' => 'デケエ', 
              'choice4' => 'ハチャラゥーン', 
              'pathPronunciation' => '', 
              'pathBackground' => '../image/myanmar/danceByEveryone.jpg', 
              'subLanguage' => '', 
              'jpGreetingWord' => '', 
            ],
            [ 'language' => 'ミャンマー語',            
              'question' => 'ミャンマー語で「何言ったの？」は？',
              'answer' => 'バーミョーライタ レ?', 
              'choice1' => 'ベ ラォ チッレー？', 
              'choice2' => 'バーミョーライタ レ?', 
              'choice3' => 'ヨォン ラー?', 
              'choice4' => 'ヨォン バー?', 
              'pathPronunciation' => '', 
              'pathBackground' => '../image/myanmar/danceByEveryone.jpg', 
              'subLanguage' => '', 
              'jpGreetingWord' => '', 
            ],
            [ 'language' => 'ミャンマー語',            
              'question' => 'ミャンマー語で「ちょっと待ってください」は？',
              'answer' => 'カナァサォパー', 
              'choice1' => 'ベ ラォ チッレー？', 
              'choice2' => 'ハチャラゥーン', 
              'choice3' => 'カナァサォパー', 
              'choice4' => 'バーミョーライタ レ', 
              'pathPronunciation' => '', 
              'pathBackground' => '../image/myanmar/danceByEveryone.jpg', 
              'subLanguage' => '', 
              'jpGreetingWord' => '', 
            ],


            


            [ 'language' => '関西弁',            
              'question' => '関西弁で「ありがとう」は？',
              'answer' => 'おおきに', 
              'choice1' => 'おおきに', 
              'choice2' => 'まいど', 
              'choice3' => 'かんにん', 
              'choice4' => 'あかん', 
              'pathPronunciation' => '', 
              'pathBackground' => '../image/myanmar/danceByEveryone.jpg', 
              'subLanguage' => '', 
              'jpGreetingWord' => '', 
            ],
            [ 'language' => '関西弁',            
            'question' => '関西弁で「本当」は？',
            'answer' => 'ほんま', 
            'choice1' => 'おおきに', 
            'choice2' => 'まいど', 
            'choice3' => 'ほな', 
            'choice4' => 'ほんま', 
            'pathPronunciation' => '', 
            'pathBackground' => '../image/myanmar/danceByEveryone.jpg', 
            'subLanguage' => '', 
            'jpGreetingWord' => '', 
          ],
            [ 'language' => '関西弁',            
              'question' => '関西弁で「じゃあ」は？',
              'answer' => 'ほな', 
              'choice1' => 'おおきに', 
              'choice2' => 'まいど', 
              'choice3' => 'かんにん', 
              'choice4' => 'ほな', 
              'pathPronunciation' => '', 
              'pathBackground' => '../image/myanmar/danceByEveryone.jpg', 
              'subLanguage' => '', 
              'jpGreetingWord' => '', 
            ],
            [ 'language' => '関西弁',            
              'question' => '関西弁で「捨てる」は？',
              'answer' => 'ほかす', 
              'choice1' => 'いらう', 
              'choice2' => 'いちびる', 
              'choice3' => 'なげる', 
              'choice4' => 'ほかす', 
              'pathPronunciation' => '', 
              'pathBackground' => '../image/myanmar/danceByEveryone.jpg', 
              'subLanguage' => '', 
              'jpGreetingWord' => '', 
            ],
            [ 'language' => '関西弁',            
              'question' => '関西弁で「ダメ」は？',
              'answer' => 'あかん', 
              'choice1' => 'あいそ', 
              'choice2' => 'いてまう', 
              'choice3' => 'かんにん', 
              'choice4' => 'あかん', 
              'pathPronunciation' => '', 
              'pathBackground' => '../image/myanmar/danceByEveryone.jpg', 
              'subLanguage' => '', 
              'jpGreetingWord' => '', 
            ],
            [ 'language' => '関西弁',            
              'question' => '関西弁で「痛い目にあわせる」は？',
              'answer' => 'いてまう', 
              'choice1' => 'あんじょう', 
              'choice2' => 'いてまう', 
              'choice3' => 'いちびり', 
              'choice4' => 'あかん', 
              'pathPronunciation' => '', 
              'pathBackground' => '../image/myanmar/danceByEveryone.jpg', 
              'subLanguage' => '', 
              'jpGreetingWord' => '', 
            ],
            [ 'language' => '関西弁',            
              'question' => '関西弁で「触る」は？',
              'answer' => 'いらう', 
              'choice1' => 'ほかす', 
              'choice2' => 'いてまう', 
              'choice3' => 'いわす', 
              'choice4' => 'いらう', 
              'pathPronunciation' => '', 
              'pathBackground' => '../image/myanmar/danceByEveryone.jpg', 
              'subLanguage' => '', 
              'jpGreetingWord' => '', 
            ],

            [ 'language' => '関西弁',            
              'question' => '関西弁で「許して」は？',
              'answer' => 'かんにん', 
              'choice1' => 'あて', 
              'choice2' => 'いてまう', 
              'choice3' => 'かんにん', 
              'choice4' => 'かなんわ', 
              'pathPronunciation' => '', 
              'pathBackground' => '../image/myanmar/danceByEveryone.jpg', 
              'subLanguage' => '', 
              'jpGreetingWord' => '', 
            ],
            [ 'language' => '関西弁',            
              'question' => '関西弁で「短気」は？',
              'answer' => 'いらち', 
              'choice1' => 'あんじょう', 
              'choice2' => 'ほかす', 
              'choice3' => 'いちびり', 
              'choice4' => 'いらち', 
              'pathPronunciation' => '', 
              'pathBackground' => '../image/myanmar/danceByEveryone.jpg', 
              'subLanguage' => '', 
              'jpGreetingWord' => '', 
            ],
            [ 'language' => '関西弁',            
              'question' => '関西弁で「たくさん」は？',
              'answer' => 'ようけ or ぎょうさん', 
              'choice1' => 'ぬくい', 
              'choice2' => 'ようけ or ぎょうさん', 
              'choice3' => 'けったい', 
              'choice4' => 'ごっつ', 
              'pathPronunciation' => '', 
              'pathBackground' => '../image/myanmar/danceByEveryone.jpg', 
              'subLanguage' => '', 
              'jpGreetingWord' => '', 
            ],

            [ 'language' => '関西弁',            
              'question' => '関西弁で「くすぐったい」は？',
              'answer' => 'こしょばい', 
              'choice1' => 'あいそ', 
              'choice2' => 'けったい', 
              'choice3' => 'こすい', 
              'choice4' => 'こしょばい', 
              'pathPronunciation' => '', 
              'pathBackground' => '../image/myanmar/danceByEveryone.jpg', 
              'subLanguage' => '', 
              'jpGreetingWord' => '', 
            ],
            [ 'language' => '関西弁',            
              'question' => '関西弁で「ふざける」は？',
              'answer' => 'ちょける', 
              'choice1' => 'あんじょう', 
              'choice2' => 'ずっこい', 
              'choice3' => 'いちびり', 
              'choice4' => 'ちょける', 
              'pathPronunciation' => '', 
              'pathBackground' => '../image/myanmar/danceByEveryone.jpg', 
              'subLanguage' => '', 
              'jpGreetingWord' => '', 
            ],
            [ 'language' => '関西弁',            
              'question' => '関西弁で「意地悪」は？',
              'answer' => 'いけず', 
              'choice1' => 'ほかす', 
              'choice2' => 'いちびり', 
              'choice3' => 'いきってる', 
              'choice4' => 'いらう', 
              'pathPronunciation' => '', 
              'pathBackground' => '../image/myanmar/danceByEveryone.jpg', 
              'subLanguage' => '', 
              'jpGreetingWord' => '', 
            ],

            [ 'language' => '関西弁',            
              'question' => '関西弁で「上手く」は？',
              'answer' => 'あんじょう', 
              'choice1' => 'まいど', 
              'choice2' => 'ちょける', 
              'choice3' => 'したって', 
              'choice4' => 'あんじょう', 
              'pathPronunciation' => '', 
              'pathBackground' => '../image/myanmar/danceByEveryone.jpg', 
              'subLanguage' => '', 
              'jpGreetingWord' => '', 
            ],

            [ 'language' => '関西弁',            
            'question' => '関西弁で「温かい」は？',
            'answer' => 'ぬくい', 
            'choice1' => 'ねくい', 
            'choice2' => 'ぬくい', 
            'choice3' => 'うくい', 
            'choice4' => 'るくい', 
            'pathPronunciation' => '', 
            'pathBackground' => '../image/myanmar/danceByEveryone.jpg', 
            'subLanguage' => '', 
            'jpGreetingWord' => '', 
          ],







            [ 'language' => '世界の挨拶',            
            'question' => '英語で「こんにちは」は？',
            'answer' => 'Hello', 
            'choice1' => 'See you', 
            'choice2' => 'Good luck', 
            'choice3' => 'Thank you', 
            'choice4' => 'Hello', 
            'pathPronunciation' => '', 
            'pathBackground' => '../image/myanmar/danceByEveryone.jpg', 
            'subLanguage' => '英語', 
            'jpGreetingWord' => 'こんにちは', 
          ],
          [ 'language' => '世界の挨拶',            
            'question' => '英語で「ありがとう」は？',
            'answer' => 'Thank you', 
            'choice1' => 'See you', 
            'choice2' => 'Good luck', 
            'choice3' => 'Thank you', 
            'choice4' => 'Hello', 
            'pathPronunciation' => '', 
            'pathBackground' => '../image/myanmar/danceByEveryone.jpg', 
            'subLanguage' => '英語', 
            'jpGreetingWord' => 'ありがとう', 
          ],
          [ 'language' => '世界の挨拶',            
            'question' => '良い一日を',
            'answer' => 'Have a nice day', 
            'choice1' => 'See you', 
            'choice2' => 'Aloha', 
            'choice3' => 'Thank you', 
            'choice4' => 'Have a nice day', 
            'pathPronunciation' => '', 
            'pathBackground' => '../image/myanmar/danceByEveryone.jpg', 
            'subLanguage' => '英語', 
            'jpGreetingWord' => '良い一日を', 
          ],
             [ 'language' => '世界の挨拶',            
               'question' => 'ミャンマー語で「こんにちは」は？',
               'answer' => 'ミンガラーバー', 
               'choice1' => 'スモガ ハリアンダ ムニュナンカン', 
               'choice2' => 'スラマッシアン', 
               'choice3' => 'チーズーべ', 
               'choice4' => 'ミンガラーバー', 
               'pathPronunciation' => '', 
               'pathBackground' => '../image/myanmar/danceByEveryone.jpg', 
               'subLanguage' => 'ミャンマー語', 
               'jpGreetingWord' => 'こんにちは', 
             ],
             [ 'language' => '世界の挨拶',            
               'question' => 'ミャンマー語で「ありがとう」は？',
               'answer' => 'ティーズーべ', 
               'choice1' => 'スモガ ハリアンダ ムニュナンカン', 
               'choice2' => 'スラマッシアン', 
               'choice3' => 'ティーズーべ', 
               'choice4' => 'ミンガラーバー', 
               'pathPronunciation' => '', 
               'pathBackground' => '../image/myanmar/danceByEveryone.jpg', 
               'subLanguage' => 'ミャンマー語', 
               'jpGreetingWord' => 'ありがとう', 
             ],
             [ 'language' => '世界の挨拶',            
               'question' => 'ミャンマー語で「良い一日を」は？',
               'answer' => 'カントン ネィ レイ ピ パスィ', 
               'choice1' => 'スモガ ハリアンダ ムニュナンカン', 
               'choice2' => 'インガット カ パラギ', 
               'choice3' => 'カントン ネィ レイ ピ パスィ', 
               'choice4' => 'テレマカシ', 
               'pathPronunciation' => '', 
               'pathBackground' => '../image/myanmar/danceByEveryone.jpg', 
               'subLanguage' => 'ミャンマー語', 
               'jpGreetingWord' => '良い一日を', 
             ],

             [ 'language' => '世界の挨拶',            
               'question' => '中国語で「こんにちは」は？',
               'answer' => 'ニーハオ', 
               'choice1' => 'アンニョンハセヨ', 
               'choice2' => 'シェイシェイ', 
               'choice3' => 'ニーハオ', 
               'choice4' => 'シェイシェイ', 
               'pathPronunciation' => '', 
               'pathBackground' => '../image/myanmar/danceByEveryone.jpg', 
               'subLanguage' => '中国語', 
               'jpGreetingWord' => 'こんにちは', 
             ],
             [ 'language' => '世界の挨拶',            
               'question' => '中国語で「ありがとう」は？',
               'answer' => 'シェイシェイ', 
               'choice1' => 'ニーハオ', 
               'choice2' => 'カムソハムニダ', 
               'choice3' => 'シェイシェイ', 
               'choice4' => 'テレマカシ', 
               'pathPronunciation' => '', 
               'pathBackground' => '../image/myanmar/danceByEveryone.jpg', 
               'subLanguage' => '中国語', 
               'jpGreetingWord' => 'ありがとう', 
             ],

             [ 'language' => '世界の挨拶',            
               'question' => '中国語で「良い一日を」は？',
               'answer' => 'ヂュウ ニィ ヨゥ ユゥ クワィ ダ イ ティン', 
               'choice1' => 'スモガ ハリアンダ ムニュナンカン', 
               'choice2' => 'ドゥーデェ', 
               'choice3' => 'ヂュウ ニィ ヨゥ ユゥ クワィ ダ イ ティン', 
               'choice4' => 'ネイホゥ', 
               'pathPronunciation' => '', 
               'pathBackground' => '../image/myanmar/danceByEveryone.jpg', 
               'subLanguage' => '中国語', 
               'jpGreetingWord' => '良い一日を',
            ],
             [ 'language' => '世界の挨拶',            
               'question' => '韓国語で「こんにちは」は？',
               'answer' => 'アンニョンハセヨ', 
               'choice1' => 'アンニョンハセヨ', 
               'choice2' => 'チョウン ハル ポネセヨ', 
               'choice3' => 'ニーハオ', 
               'choice4' => 'カムソハムニダ', 
               'pathPronunciation' => '', 
               'pathBackground' => '../image/myanmar/danceByEveryone.jpg', 
               'subLanguage' => '韓国語', 
               'jpGreetingWord' => 'こんにちは', 
             ],
             [ 'language' => '世界の挨拶',            
               'question' => '韓国語で「ありがとう」は？',
               'answer' => 'カムソハムニダ', 
               'choice1' => 'ニーハオ', 
               'choice2' => 'チョウン ハル ポネセヨ', 
               'choice3' => 'アンニョンハセヨ', 
               'choice4' => 'カムソハムニダ', 
               'pathPronunciation' => '', 
               'pathBackground' => '../image/myanmar/danceByEveryone.jpg', 
               'subLanguage' => '韓国語', 
               'jpGreetingWord' => 'ありがとう', 
             ],
             [ 'language' => '世界の挨拶',            
               'question' => '韓国語で「良い一日を」は？',
               'answer' => 'チョウン ハル ポネセヨ', 
               'choice1' => 'ネイホゥ', 
               'choice2' => 'インガット カ パラギ', 
               'choice3' => 'ドゥーデェ', 
               'choice4' => 'チョウン ハル ポネセヨ', 
               'pathPronunciation' => '', 
               'pathBackground' => '../image/myanmar/danceByEveryone.jpg', 
               'subLanguage' => '韓国語', 
               'jpGreetingWord' => '良い一日を', 
             ],

             [ 'language' => '世界の挨拶',            
               'question' => 'タガログ語で「こんにちは」は？',
               'answer' => 'マガンダング ハーポン', 
               'choice1' => 'マガンダング ハーポン', 
               'choice2' => 'サラマットゥ', 
               'choice3' => 'スラマッパタン', 
               'choice4' => 'サワディー + カップ(男)/ カー(女)', 
               'pathPronunciation' => '', 
               'pathBackground' => '../image/myanmar/danceByEveryone.jpg', 
               'subLanguage' => 'タガログ語', 
               'jpGreetingWord' => 'こんにちは', 
             ],
             [ 'language' => '世界の挨拶',            
               'question' => 'タガログ語で「ありがとう」は？',
               'answer' => 'サラマットゥ', 
               'choice1' => 'サラマットゥ', 
               'choice2' => 'コープン + カップ(男)/ カー(女)', 
               'choice3' => 'ドゥーデェ', 
               'choice4' => 'テレマカシ', 
               'pathPronunciation' => '', 
               'pathBackground' => '../image/myanmar/danceByEveryone.jpg', 
               'subLanguage' => 'タガログ語', 
               'jpGreetingWord' => 'ありがとう', 
             ],
             [ 'language' => '世界の挨拶',            
               'question' => 'タガログ語で「良い一日を」は？',
               'answer' => 'インガットゥ カ パ ラギ', 
               'choice1' => 'スモガ ハリアンダ ムニュナンカン', 
               'choice2' => 'ケテンガ ブエンディーア', 
               'choice3' => 'チョークディーナ + カップ(男)/ カー(女)', 
               'choice4' => 'インガットゥ カ パ ラギ', 
               'pathPronunciation' => '', 
               'pathBackground' => '../image/myanmar/danceByEveryone.jpg', 
               'subLanguage' => 'タガログ語', 
               'jpGreetingWord' => '良い一日を', 
             ],

             [ 'language' => '世界の挨拶',            
               'question' => 'タイ語で「こんにちは」は？',
               'answer' => 'サワディー + カップ(男)/ カー(女)', 
               'choice1' => 'マガンダング ハーポン', 
               'choice2' => 'コープン + カップ(男)/ カー(女)', 
               'choice3' => 'スラマッパタン', 
               'choice4' => 'サワディー + カップ(男)/ カー(女)', 
               'pathPronunciation' => '', 
               'pathBackground' => '../image/myanmar/danceByEveryone.jpg', 
               'subLanguage' => 'タイ語', 
               'jpGreetingWord' => 'こんにちは', 
             ],
             [ 'language' => '世界の挨拶',            
               'question' => 'タイ語で「ありがとう」は？',
               'answer' => 'コープン + カップ(男)/ カー(女)', 
               'choice1' => 'サラマットゥ', 
               'choice2' => 'コープン + カップ(男)/ カー(女)', 
               'choice3' => 'サワディー + カップ(男)/ カー(女)', 
               'choice4' => 'テレマカシ', 
               'pathPronunciation' => '', 
               'pathBackground' => '../image/myanmar/danceByEveryone.jpg', 
               'subLanguage' => 'タイ語', 
               'jpGreetingWord' => 'ありがとう', 
             ],
             [ 'language' => '世界の挨拶',            
               'question' => 'タイ語で「良い一日を」は？',
               'answer' => 'チョークディーナ + カップ(男)/ カー(女)', 
               'choice1' => 'スモガ ハリアンダ ムニュナンカン', 
               'choice2' => 'コープン + カップ(男)/ カー(女)', 
               'choice3' => 'チョークディーナ + カップ(男)/ カー(女)', 
               'choice4' => 'サワディー + カップ(男)/ カー(女)', 
               'pathPronunciation' => '', 
               'pathBackground' => '../image/myanmar/danceByEveryone.jpg', 
               'subLanguage' => 'タイ語', 
               'jpGreetingWord' => '良い一日を', 
             ],


             [ 'language' => '世界の挨拶',            
               'question' => 'インドネシア語で「こんにちは」は？',
               'answer' => 'スラマッシアン', 
               'choice1' => 'マガンダング ハーポン', 
               'choice2' => 'スラマッシアン', 
               'choice3' => 'スラマッパタン', 
               'choice4' => 'サワディー + カップ(男)/ カー(女)', 
               'pathPronunciation' => '', 
               'pathBackground' => '../image/myanmar/danceByEveryone.jpg', 
               'subLanguage' => 'インドネシア語', 
               'jpGreetingWord' => 'こんにちは', 
             ],
             [ 'language' => '世界の挨拶',            
               'question' => 'インドネシア語で「ありがとう」は？',
               'answer' => 'テレマカシ', 
               'choice1' => 'サラマットゥ', 
               'choice2' => 'コープン + カップ(男)/ カー(女)', 
               'choice3' => 'タンキュー', 
               'choice4' => 'テレマカシ', 
               'pathPronunciation' => '', 
               'pathBackground' => '../image/myanmar/danceByEveryone.jpg', 
               'subLanguage' => 'インドネシア語', 
               'jpGreetingWord' => 'ありがとう', 
             ],


             [ 'language' => '世界の挨拶',            
               'question' => 'インドネシア語で「良い一日を」は？',
               'answer' => 'スモガ ハリアンダ ムニュナンカン', 
               'choice1' => 'スモガ ハリアンダ ムニュナンカン', 
               'choice2' => 'インガットゥ カ パ ラギ', 
               'choice3' => 'チョークディーナ + カップ(男)/ カー(女)', 
               'choice4' => 'ケテンガ ブエンディーア', 
               'pathPronunciation' => '', 
               'pathBackground' => '../image/myanmar/danceByEveryone.jpg', 
               'subLanguage' => 'インドネシア語', 
               'jpGreetingWord' => '良い一日を', 
             ],

             [ 'language' => '世界の挨拶',            
               'question' => 'イタリア語で「こんにちは」は？',
               'answer' => 'チャオ', 
               'choice1' => 'シンチャオ', 
               'choice2' => 'チャオ', 
               'choice3' => 'オラ', 
               'choice4' => 'ボンジュール', 
               'pathPronunciation' => '', 
               'pathBackground' => '../image/myanmar/danceByEveryone.jpg', 
               'subLanguage' => 'イタリア語', 
               'jpGreetingWord' => 'こんにちは', 
             ],
             [ 'language' => '世界の挨拶',            
               'question' => 'イタリア語で「ありがとう」は？',
               'answer' => 'グラッツェ', 
               'choice1' => 'グラシアス', 
               'choice2' => 'ダンケシェン', 
               'choice3' => 'チャオ', 
               'choice4' => 'グラッツェ', 
               'pathPronunciation' => '', 
               'pathBackground' => '../image/myanmar/danceByEveryone.jpg', 
               'subLanguage' => 'イタリア語', 
               'jpGreetingWord' => 'ありがとう', 
             ],


             [ 'language' => '世界の挨拶',            
               'question' => 'イタリア語で「良い一日を」は？',
               'answer' => 'ブオナ ジョルナータ', 
               'choice1' => 'ブオナ ジョルナータ', 
               'choice2' => 'アイネン シューネンターク', 
               'choice3' => 'ボンジョルネ', 
               'choice4' => 'ケテンガ ブエンディーア', 
               'pathPronunciation' => '', 
               'pathBackground' => '../image/myanmar/danceByEveryone.jpg', 
               'subLanguage' => 'イタリア語', 
               'jpGreetingWord' => '良い一日を', 
             ],
             [ 'language' => '世界の挨拶',            
             'question' => 'スペイン語で「こんにちは」は？',
             'answer' => 'オラ or ブエナス タルデス', 
             'choice1' => 'ボンジュール', 
             'choice2' => 'チャオ', 
             'choice3' => 'グーテンターク', 
             'choice4' => 'オラ or ブエナス タルデス', 
             'pathPronunciation' => '', 
             'pathBackground' => '../image/myanmar/danceByEveryone.jpg', 
             'subLanguage' => 'スペイン語', 
             'jpGreetingWord' => 'こんにちは', 
           ],
           [ 'language' => '世界の挨拶',            
             'question' => 'スペイン語で「ありがとう」は？',
             'answer' => 'グラシアス', 
             'choice1' => 'グラシアス', 
             'choice2' => 'ダンケシェン', 
             'choice3' => 'チャオ', 
             'choice4' => 'グラッツェ', 
             'pathPronunciation' => '', 
             'pathBackground' => '../image/myanmar/danceByEveryone.jpg', 
             'subLanguage' => 'スペイン語', 
             'jpGreetingWord' => 'ありがとう', 
           ],


           [ 'language' => '世界の挨拶',            
             'question' => 'スペイン語で「良い一日を」は？',
             'answer' => 'ケテンガ ブエンディーア', 
             'choice1' => 'ブオナ ジョルナータ', 
             'choice2' => 'アイネン シューネンターク', 
             'choice3' => 'ボンジョルネ', 
             'choice4' => 'ケテンガ ブエンディーア', 
             'pathPronunciation' => '', 
             'pathBackground' => '../image/myanmar/danceByEveryone.jpg', 
             'subLanguage' => 'スペイン語', 
             'jpGreetingWord' => '良い一日を', 
           ],
           [ 'language' => '世界の挨拶',            
           'question' => 'フランス語で「こんにちは」は？',
           'answer' => 'ボンジュール', 
           'choice1' => 'ボンジョルネ', 
           'choice2' => 'チャオ', 
           'choice3' => 'グーテンターク', 
           'choice4' => 'ボンジュール', 
           'pathPronunciation' => '', 
           'pathBackground' => '../image/myanmar/danceByEveryone.jpg', 
           'subLanguage' => 'フランス語', 
           'jpGreetingWord' => 'こんにちは', 
         ],
         [ 'language' => '世界の挨拶',            
           'question' => 'フランス語で「ありがとう」は？',
           'answer' => 'メルシー', 
           'choice1' => 'グラシアス', 
           'choice2' => 'メルシー', 
           'choice3' => 'チャオ', 
           'choice4' => 'グラッツェ', 
           'pathPronunciation' => '', 
           'pathBackground' => '../image/myanmar/danceByEveryone.jpg', 
           'subLanguage' => 'フランス語', 
           'jpGreetingWord' => 'ありがとう', 
         ],


         [ 'language' => '世界の挨拶',            
           'question' => 'フランス語で「良い一日を」は？',
           'answer' => 'ボンジョルネ', 
           'choice1' => 'ブオナ ジョルナータ', 
           'choice2' => 'アイネン シューネンターク', 
           'choice3' => 'ボンジョルネ', 
           'choice4' => 'コマンタレヴー', 
           'pathPronunciation' => '', 
           'pathBackground' => '../image/myanmar/danceByEveryone.jpg', 
           'subLanguage' => 'フランス語', 
           'jpGreetingWord' => '良い一日を', 
         ],

         [ 'language' => '世界の挨拶',            
           'question' => 'ドイツ語で「こんにちは」は？',
           'answer' => 'グーテンターク', 
           'choice1' => 'ボンジョルネ', 
           'choice2' => 'チャオ', 
           'choice3' => 'グーテンターク', 
           'choice4' => 'ボンジュール', 
           'pathPronunciation' => '', 
           'pathBackground' => '../image/myanmar/danceByEveryone.jpg', 
           'subLanguage' => 'ドイツ語', 
           'jpGreetingWord' => 'こんにちは', 
         ],
         [ 'language' => '世界の挨拶',            
           'question' => 'ドイツ語で「ありがとう」は？',
           'answer' => 'ダンケシェン', 
           'choice1' => 'グラシアス', 
           'choice2' => 'メルシー', 
           'choice3' => 'ダンケシェン', 
           'choice4' => 'グラッツェ', 
           'pathPronunciation' => '', 
           'pathBackground' => '../image/myanmar/danceByEveryone.jpg', 
           'subLanguage' => 'ドイツ語', 
           'jpGreetingWord' => 'ありがとう', 
         ],


         [ 'language' => '世界の挨拶',            
           'question' => 'ドイツ語で「良い一日を」は？',
           'answer' => 'アイネン シューネンターク', 
           'choice1' => 'ブオナ ジョルナータ', 
           'choice2' => 'アイネン シューネンターク', 
           'choice3' => 'ボンジョルネ', 
           'choice4' => 'コマンタレヴー', 
           'pathPronunciation' => '', 
           'pathBackground' => '../image/myanmar/danceByEveryone.jpg', 
           'subLanguage' => 'ドイツ語', 
           'jpGreetingWord' => '良い一日を', 
         ],

            //  [ 'language' => 'ミャンマー語',            
            //    'question' => 'ミャンマー語で「」は？',
            //    'answer' => '', 
            //    'choice1' => '', 
            //    'choice2' => '', 
            //    'choice3' => '', 
            //    'choice4' => '', 
            //    'pathPronunciation' => '', 
            //    'pathBackground' => '../image/myanmar/danceByEveryone.jpg', 
            //  ],
            //   [ 'language' => 'ミャンマー語',            
            //    'question' => 'ミャンマー語で「」は？',
            //    'answer' => '', 
            //    'choice1' => '', 
            //    'choice2' => '', 
            //    'choice3' => '', 
            //    'choice4' => '', 
            //    'pathPronunciation' => '', 
            //    'pathBackground' => '../image/myanmar/danceByEveryone.jpg', 
            //  ],
            //  [ 'language' => 'ミャンマー語',            
            //    'question' => 'ミャンマー語で「」は？',
            //    'answer' => '', 
            //    'choice1' => '', 
            //    'choice2' => '', 
            //    'choice3' => '', 
            //    'choice4' => '', 
            //    'pathPronunciation' => '', 
            //    'pathBackground' => '../image/myanmar/danceByEveryone.jpg', 
            //  ],
            //  [ 'language' => 'ミャンマー語',            
            //    'question' => 'ミャンマー語で「」は？',
            //    'answer' => '', 
            //    'choice1' => '', 
            //    'choice2' => '', 
            //    'choice3' => '', 
            //    'choice4' => '', 
            //    'pathPronunciation' => '', 
            //    'pathBackground' => '../image/myanmar/danceByEveryone.jpg', 
            //  ],
            //  [ 'language' => 'ミャンマー語',            
            //    'question' => 'ミャンマー語で「」は？',
            //    'answer' => '', 
            //    'choice1' => '', 
            //    'choice2' => '', 
            //    'choice3' => '', 
            //    'choice4' => '', 
            //    'pathPronunciation' => '', 
            //    'pathBackground' => '../image/myanmar/danceByEveryone.jpg', 
            //  ],
            //  [ 'language' => 'ミャンマー語',            
            //  'question' => 'ミャンマー語で「」は？',
            //  'answer' => '', 
            //  'choice1' => '', 
            //  'choice2' => '', 
            //  'choice3' => '', 
            //  'choice4' => '', 
            //  'pathPronunciation' => '', 
            //  'pathBackground' => '../image/myanmar/danceByEveryone.jpg', 
            //  ],
            //  [ 'language' => 'ミャンマー語',            
            //    'question' => 'ミャンマー語で「」は？',
            //    'answer' => '', 
            //    'choice1' => '', 
            //    'choice2' => '', 
            //    'choice3' => '', 
            //    'choice4' => '', 
            //    'pathPronunciation' => '', 
            //    'pathBackground' => '../image/myanmar/danceByEveryone.jpg', 
            //  ],


        ]);    
    }
}
